package com.example.demo.repository.entities;
// Generated Mar 9, 2023, 7:47:10 AM by Hibernate Tools 6.2.0.CR1


import jakarta.persistence.*;

import java.util.HashSet;
import java.util.Set;

import static jakarta.persistence.GenerationType.IDENTITY;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name="role"
    ,catalog="flamingoo"
)
public class Role  implements java.io.Serializable {


     private int id;
     private String name;
     private Set<User> users = new HashSet<>(0);

    public Role() {
    }

	
    public Role(int id, String name) {
        this.id = id;
        this.name = name;
    }
    public Role(int id, String name, Set<User> users) {
       this.id = id;
       this.name = name;
       this.users = users;
    }
   
     @Id

     @GeneratedValue(strategy= IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="user_has_roles", catalog="flamingoo", joinColumns = { 
        @JoinColumn(name="roles_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="user_id", nullable=false, updatable=false) })
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }




}


