package com.example.demo.repository.entities;
// Generated Mar 9, 2023, 7:47:10 AM by Hibernate Tools 6.2.0.CR1


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * UserReviewProduct generated by hbm2java
 */
@Entity
@Table(name="user_review_product"
    ,catalog="flamingoo"
)
public class UserReviewProduct  implements java.io.Serializable {


     private int reviewId;
     private Product product;
     private User user;
     private Short reviewRating;
     private String reviewDescription;

    public UserReviewProduct() {
    }

	
    public UserReviewProduct(int reviewId, Product product, User user) {
        this.reviewId = reviewId;
        this.product = product;
        this.user = user;
    }
    public UserReviewProduct(int reviewId, Product product, User user, Short reviewRating, String reviewDescription) {
       this.reviewId = reviewId;
       this.product = product;
       this.user = user;
       this.reviewRating = reviewRating;
       this.reviewDescription = reviewDescription;
    }
   
     @Id 

    
    @Column(name="review_id", unique=true, nullable=false)
    public int getReviewId() {
        return this.reviewId;
    }
    
    public void setReviewId(int reviewId) {
        this.reviewId = reviewId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="product_id", nullable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="review_rating")
    public Short getReviewRating() {
        return this.reviewRating;
    }
    
    public void setReviewRating(Short reviewRating) {
        this.reviewRating = reviewRating;
    }

    
    @Column(name="review_description", length=45)
    public String getReviewDescription() {
        return this.reviewDescription;
    }
    
    public void setReviewDescription(String reviewDescription) {
        this.reviewDescription = reviewDescription;
    }




}


